import { makeThemedStyles } from '../makeThemedStyles';

export const filterSearchBarStyles = makeThemedStyles((t) => ({
    container: {
        marginHorizontal: t.spacing.d,
        marginTop: t.spacing.b,
        marginBottom: t.spacing.aSmall,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: t.color.containerDefault,
        borderRadius: t.radius.roundedC,
        borderWidth: 1,
        borderColor: t.color.borderDefault,
        paddingHorizontal: t.spacing.c,
        height: 48,
    },
    searchIcon: {
        width: t.spacing.d,
        height: t.spacing.d,
        marginRight: t.spacing.b,
    },
    input: {
        flex: 1,
        fontSize: t.fontSize.size14,
        fontFamily: t.fontFamily.primary,
        color: t.color.contentDefault,
        paddingVertical: 0,
    },
    filterButton: {
        width: 44,
        height: 44,
        borderRadius: t.radius.roundedB,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: t.spacing.b,
        backgroundColor: t.color.containerStrong,
    },
    activeFilterButton: {
        backgroundColor: t.color.interactiveBrand,
    },
    badge: {
        position: 'absolute',
        top: -t.spacing.a,
        right: -t.spacing.a,
        backgroundColor: t.color.interactiveBrand,
        borderRadius: t.radius.roundedB,
        minWidth: t.spacing.d,
        height: t.spacing.d,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: t.spacing.a,
    },
    badgeText: {
        fontSize: t.fontSize.size12,
        fontFamily: t.fontFamily.bold,
        color: t.color.contentInverseSolid,
    },
    clearButton: {
        width: 44,
        height: 44,
        borderRadius: t.radius.roundedE,
        backgroundColor: t.color.borderStrong,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: t.spacing.b,
    },
    clearText: {
        fontSize: t.fontSize.size14,
        fontWeight: 'bold',
        color: t.color.contentInverseSolid,
        lineHeight: t.lineHeight.lh16,
    },
    clearXBar: {
        width: t.spacing.b,
        height: t.spacing.aSmall,
        backgroundColor: t.color.contentInverseSolid,
    },
    clearXBarSecond: {
        width: t.spacing.b,
        height: t.spacing.aSmall,
        backgroundColor: t.color.contentInverseSolid,
        marginTop: -t.spacing.aSmall,
    },
}));
