export const cuisineEmojiMatch: { [key: string]: string } = {
    'fish & chips': '🐟🍟',
    'curry': '🍛',
    'groceries': '🛍️',
    'low delivery fee': '💸',
    'shops': '🛒',
    'collect stamps': '📮',
    'deals': '🤑',
    'pharmacy': '💊',
    'alcohol': '🍺',
    'pizza': '🍕',
    'off': '💲',
    'halal': 'حلال',
    'burger': '🍔',
    'chicken': '🍗',
    'convenience': '🏪',
    'local legends': '👑',
    'sandwich': '🥪',
    'kebab': '🍖',
    'breakfast': '🍳',
    'desserts': '🍰',
    'sushi': '🍣',
    'coffee': '☕',
    'indian': '🇮🇳',
    'chinese': '🥡',
    'milkshakes': '🥤',
    'doughnuts': '🍩',
    'bakery': '🍞',
    'steak': '🥩',
    'pasta': '🍝',
    'thai': '🇹🇭',
    'american': '🇺🇸',
    'south america': '🌎',
    'italian': '🇮🇹',
    'japanese': '🇯🇵',
    'freebies': '🆓',
    'dinner': '🍽️',
    'asia': '🥢',
    'leban': '🇱🇧',
    'grill': '🔥',
    'noodle': '🍜',
    'ramen': '🍜',
    'health': '💚',
    'gree': '🇬🇷',
    'turk': '🇹🇷',
    'caribb': '🏝️',
    'mexi': '🇲🇽',
    'burrito': '🌯',
    'jamaica': '🇯🇲',
    'mediterranean': '⛵',
    'korea': '🇰🇷',
    'jerk': '🐂',
    'africa': '🌍',
    'nigeria': '🇳🇬',
    'electron': '📱',
    'salad': '🥗',
    'venezue': '🇻🇪',
    'veg': '🥑',
    'wrap': '🌯',
    'pakist': '🇵🇰',
    'peri peri': '🌶️🍗',
    'waffle': '🧇',
    'poke': '🍚',
    'oriental': '🏮',
    'glutenfree': '🌾❌',
    'gluten free': '🌾❌',
    'gluten-free': '🌾❌',
    'streetfood': '🛖',
    'street food': '🛖',
    'street-food': '🛖',
    'european': '🇪🇺',
    'fusion': '🔄🍽️',
    'french': '🇫🇷',
    'gourmet': '👨‍🍳',
    'cafe': '☕🍰',
    'vietnamese': '🇻🇳',
    'hot-dogs': '🌭',
    'hot dogs': '🌭',
    'hotdogs': '🌭',
    'bagels': '🥯',
    'bubble-tea': '🧋',
    'bubble tea': '🧋',
    'smoothies': '🥤',
    'gifts': '🎁',
    'moroccan': '🇲🇦',
    'british': '🇬🇧',
    'pies': '🥧',
    'pubfood': '🍺🍔',
    'pub food': '🍺🍔',
    'persian': '🇮🇷',
    'drinks': '🍹',
    'biryani': '🍚🌶️',
    'middle-eastern': '🕌',
    'middle eastern': '🕌',
    'cantonese': '🥢🥟',
    'brunch': '🍳☕',
    'bangladeshi': '🇧🇩',
    'baguettes': '🥖',
    'pancakes': '🥞',
    'dim-sum': '🥟',
    'dim sum': '🥟',
    'nepalese': '🇳🇵',
    'health-and-beauty': '💄',
    'health and beauty': '💄',
    'seafood': '🦞',
    'peruvian': '🇵🇪',
    'tapas': '🇪🇸🍢',
    'portuguese': '🇵🇹',
    'fastfood': '🍟🍔',
    'fast food': '🍟🍔',
    'cakes': '🎂',
    'argentinian': '🇦🇷',
    'polish': '🇵🇱',
    'german': '🇩🇪',
    'icecream': '🍦',
    'ice cream': '🍦',
    'ice-cream': '🍦',
    'sri-lankan': '🇱🇰',
    'sri lankan': '🇱🇰',
    'taiwanese': '🇹🇼',
    'syrian': '🇸🇾',
    'filipino': '🇵🇭',
    'frozenyogurt': '🍦🥛',
    'frozen yogurt': '🍦🥛',
    'eastern-european': '🏰',
    'eastern european': '🏰',
    'pan-asian': '🥢🍲',
    'pan asian': '🥢🍲',
    'australian': '🇦🇺',
    'bbq': '🍖🔥',
    'sweets': '🍬',
    'ukrainian': '🇺🇦',
    'brazilian': '🇧🇷',
    'brazilian-food': '🇧🇷',
    'ethiopian': '🇪🇹',
    'singapore': '🇸🇬',
    'malaysian': '🇲🇾',
    'south-indian': '🍛🇮🇳',
    'south indian': '🍛🇮🇳',
    'latinamerican': '🌮🌯',
    'latin american': '🌮🌯',
    'indo-chinese-fusion': '🇮🇳🇨🇳',
    'indo chinese fusion': '🇮🇳🇨🇳',
    'ghanaian': '🇬🇭',
    'continental': '🌍🍽️',
    'spanish': '🇪🇸',
    'columbian': '🇨🇴',
    'colombian': '🇨🇴',
    'west-african': '🌍🌴',
    'west african': '🌍🌴',
    'crepes': '🥞',
    'indonesian': '🇮🇩',
    'roast-dinners': '🍗🔥',
    'roast dinners': '🍗🔥',
    'paninis': '🥪',
    'authentic-pizza': '🍕👨‍🍳',
    'authentic pizza': '🍕👨‍🍳',
    'business-lunch': '💼🍽️',
    'business lunch': '💼🍽️',
    'texmex': '🌮🇺🇸',
    'tex-mex': '🌮🇺🇸',
    'tex mex': '🌮🇺🇸',
    'flowers': '💐',
    'english-breakfast': '🇬🇧🍳',
    'english breakfast': '🇬🇧🍳',
    'kurdish': '🏔️',
    'iranian': '🇮🇷',
    'allnightalcohol': '🌙🍺',
    'all night alcohol': '🌙🍺',
    'new': '🆕',
    'with_discounts': '💯',
    'with discounts': '💯',
    'favouritespersonalised': '❤️',
    'favorites personalized': '❤️',
    'four_star': '⭐⭐⭐⭐',
    'four star': '⭐⭐⭐⭐',
    'collection': '📚',
  };
